todo/config/routes.rb
Todo::Application.routes.draw do
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

	controller :home do
		post 'assign_list_id' => :assign_list_id
	end

	controller :application do
		get 'search_for_user' => :search_for_user
		get 'email_reminder' => :email_all_users
	end

  resources :items

  resources :lists

  resources :permissions

  resources :users

  get "home/index"

  root :to => "home#index"

end

todo/app/models/user.rb
# Code taken from Ruby-on-Rails guide
# http://guides.rubyonrails.org/active_record_validations_callbacks.html 

require 'digest/sha2'

class EmailValidator < ActiveModel::Validator
	def validate(record)
		@value = record.email
		unless @value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
			record.errors[:email] << ("is not an email")
		end
	end
end

class UsernameValidator < ActiveModel::Validator
	def validate(record)
		@value = record.username
		unless @value =~ /\A[a-z0-9_]+\Z/i
			record.errors[:username] << ("contains invalid characters")
		end
	end
end

class User < ActiveRecord::Base
	include ActiveModel::Validations
	attr_accessible :username, :email, :password, :password_confirmation, :email_confirmation
	validates :username, :presence => true, :length => {:within => 4..32}, :uniqueness => true
	validates :password, :presence => true, :length => {:within => 6..64}, :confirmation => true
	validates :password_confirmation, :presence => true, :length => {:within => 6..64}
	validates :email, :presence => true, :length => {:maximum => 64}, :uniqueness => true, :confirmation => true
	validates :email_confirmation, :presence => true, :length => {:maximum => 64}
	validates_with EmailValidator, :if => "email?"
	validates_with UsernameValidator, :if => "username?"

	#automatically generate salt and encrypts password
	before_save :encrypt_password
	before_destroy :delete_list_if_user_is_only_owner

	#Validations for referential integrity follow
	has_many :permissions, :dependent => :destroy
	has_many :lists, :through => :permissions

	def authenticate?(sub_password)
		password == encrypt(sub_password)
	end

	private 
		def encrypt_password
			self.salt = make_salt if new_record? 
			self.password = encrypt(password)
		end
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
			#secure_hash to get a hash of current time
		end
		def encrypt(string)
			temp_string = string
			for i in 1..3 do 
				temp_string = secure_hash("#{salt}--#{temp_string}") 
			end
			temp_string
		end
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		def delete_list_if_user_is_only_owner
			sql_find_lists = "SELECT l.* FROM lists l, permissions p WHERE p.own = 't' AND l.id = p.list_id AND p.user_id = " + id.to_s
			#not neat but I got incorrect behaviour when using other notation [string, args]
			puts 'entering this method!'
			del_candidates = List.find_by_sql sql_find_lists
			del_candidates.each do |l|
				perms = Permission.find_by_sql ["SELECT * FROM permissions WHERE list_id = ? AND own = 't'", l.id]
				if perms.size == 1
					puts l.id
					l.destroy
				end
			end
		end
end

todo/app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_filter :authorize, :only => [:new, :create]
	before_filter :admin, :except => [:new, :create, :show, :update, :edit]
	# GET /users
	# GET /users.xml
	def index
		@users = User.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @users }
		end
	end

	# GET /users/1
	# GET /users/1.xml
	def show
		@is_admin = is_admin?(session[:user_id])
		@user = @is_admin ? User.find(params[:id]) : User.find(session[:user_id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml	{ render :xml => @user }
		end
	end

	# GET /users/new
	# GET /users/new.xml
	def new
		self.class.layout('embed')
		@user = User.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml	{ render :xml => @user }
		end
	end

	# GET /users/1/edit
	def edit
		@is_admin = is_admin?(session[:user_id])
		@user = @is_admin ? User.find(params[:id]) : User.find(session[:user_id])
	end

	# POST /users
	# POST /users.xml
	def create
		self.class.layout('embed')
		@user = User.new(params[:user])

		respond_to do |format|
			if @user.save
				format.html	{ redirect_to(new_user_path, :notice => 'User was successfully created.') }
				format.xml	{ render :xml => @user, :status => :created, :location => @user }
			else
				format.html	{ render :action => "new" }
				format.xml	{ render :xml => @user.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /users/1
	# PUT /users/1.xml
	def update
		if !is_admin?(session[:user_id]) and session[:user_id].to_i.to_s != params[:id].to_i.to_s
			@user = User.find(session[:user_id])
			respond_to do |format|
				format.html	{ render :action => "show" }
				format.xml  { render :xml => @user }
			end
		else
			@user = User.find(params[:id])

			respond_to do |format|
				if @user.update_attributes(params[:user])
					format.html	{ redirect_to(@user, :notice => 'User was successfully updated.') }
					format.xml	{ head :ok }
				else
					format.html	{ render :action => "edit" }
					format.xml	{ render :xml => @user.errors, :status => :unprocessable_entity }
				end
			end
		end
	end

	# DELETE /users/1
	# DELETE /users/1.xml
	def destroy
		@user = User.find(params[:id])
		@user.destroy

		respond_to do |format|
			format.html	{ redirect_to(users_url) }
			format.xml	{ head :ok }
		end
	end
end

todo/app/helpers/users_helper.rb
module UsersHelper
end

todo/app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'iform' } do |f| %>
	<% if @user.errors.any? %>
		<div class="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> encountered:</h2>

			<ul class="logo">
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :username %>
		<div><%= f.text_field :username %></div>
	</div>
	<div class="field">
		<%= f.label :password %>
		<div><%= f.password_field :password, :value => "" %></div>
	</div>
	<div class="field">
		<%= f.label :new_password_confirmation %>
		<div><%= f.password_field :password_confirmation %></div>
	</div>
	<div class="field">
		<%= f.label :email %>
		<div><%= f.text_field :email %></div>
	</div>
	<div class="field">
		<%= f.label :email_confirmation %>
		<div><%= f.text_field :email_confirmation, :value => @user.email %></div>
	</div>
	<%= f.submit %>
<% end %>

todo/app/views/users/_signup.html.erb
<%= form_for @user, :html => { :class => 'iform', :onsubmit => "return validate_registration();" } do |f| %>
	<header>
		<h1>Forget-Me-Not Sign Up</h1>
		<p>Register and share lists with your friends!</p>
	</header>

	<% if @user.errors.any? %>
	<div class="error_explanation">
		<h2><%= pluralize(@user.errors.count, "error") %> encountered:</h2>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<% if flash[:notice] %>
	<p class="notice"><%= flash[:notice] %></p>
	<% end %>

	<div class="field">
		<label for="user_username">Username <small>Enter a username</small></label>
		<div><%= f.text_field :username, :required => 'required', :size => '22', :maxlength => '32', :title => 'Please enter a username of length at least 4 and consisting of only letters, numbers and underscores', :pattern => '[\w]{4,32}' %></div>
	</div>

	<div class="field">
		<label for="user_email">Email <small>Enter your email address</small></label>
		<div><%= f.email_field :email, :required => 'required', :size => '22', :maxlength => '64', :title => 'Please enter your email address', :pattern => '([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})' %></div>
	</div>

	<div class="field">
		<label for="user_email_confirmation">Confirm Email <small>Confirm email address</small></label>
		<div><%= f.email_field :email_confirmation, :required => 'required', :size => '22', :maxlength => '64', :title => 'Please confirm the email address above', :pattern => '([^@\s]+)@((?:[-a-zA-Z0-9]+\.)+[a-zA-Z]{2,})' %></div>
	</div>

	<div class="field">
		<label for="user_password">Password <small>Minimum of 6 characters</small></label>
		<div><%= f.password_field :password, :required => 'required', :size => '22', :maxlength => '64', :title => 'Please enter a password of length at least 6', :pattern => '.{6,64}' %></div>
	</div>

	<div class="field">
		<label for="user_password_confirmation">Confirm Password <small>Confirm password</small></label>
		<div><%= f.password_field :password_confirmation, :required => 'required', :size => '22', :maxlength => '64', :title => 'Please confirm the password above', :pattern => '.{6,64}' %></div>
	</div>

	<%= f.submit :value => 'Sign Up' %>
<% end %>

todo/app/views/users/edit.html.erb
<div class="doc">

<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', @is_admin ? users_path : root_url %>

</div>

todo/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
	<tr>
		<th>Username</th>
		<th>Email</th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

<% @users.each do |user| %>
	<tr>
		<td><%= user.username %></td>
		<td><%= user.email %></td>
		<td><%= link_to 'Show', user %></td>
		<td><%= link_to 'Edit', edit_user_path(user) %></td>
		<td><%= button_to 'Destroy', user, :method => :delete	%></td>
	</tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

todo/app/views/users/new.html.erb
<%= render 'signup' %>

todo/app/views/users/show.html.erb
<div class="doc">

<p id="notice"><%= notice %></p>

<p>
	<b>Username:</b>
	<%= @user.username %>
</p>

<% if @is_admin %>
<p>
	<b>Password:</b>
	<%= @user.password %>
</p>

<p>
	<b>Salt:</b>
	<%= @user.salt %>
</p>
<% end %>

<p>
	<b>Email:</b>
	<%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_url %>

</div>