todo/config/routes.rb
Todo::Application.routes.draw do
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

	controller :home do
		post 'assign_list_id' => :assign_list_id
	end

	controller :application do
		get 'search_for_user' => :search_for_user
		get 'email_reminder' => :email_all_users
	end

  resources :items

  resources :lists

  resources :permissions

  resources :users

  get "home/index"

  root :to => "home#index"

end

todo/app/models/permission.rb
class Permission < ActiveRecord::Base
	validates :user_id, :presence => true, :uniqueness => { :scope => :list_id }
	validates :list_id, :presence => true, :uniqueness => { :scope => :user_id }
	validates :user, :presence => { :message => "should be an existing user" }
	validates :list, :presence => { :message => "should be an existing list" }

	validate :user_is_not_only_owner, :on => :update, :if => "own_changed?"
	before_destroy :user_is_not_only_owner
	validate :owner_has_all_permissions

	belongs_to :user
	belongs_to :list
	
	private 

		def user_is_not_only_owner
			if own
				perms = Permission.find_by_sql ["SELECT * FROM permissions WHERE list_id = ? AND own = 't'", list_id.to_s]
				puts list_id.to_s
				errors[:own] << (" -- You are the last owner of the list!" + 
						" Please assign someone else ownership before you change your permissions.") if perms.size == 1
			end
		end

		def owner_has_all_permissions
			if own
				unless add and edit and del
					errors[:own] << ("as the list owner, you must give yourself all possible permissions")
				end
			end
		end
end

todo/app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
	layout 'embed'

	# GET /permissions
	# GET /permissions.xml
	def index
		@permissions = (session[:list_id]) ? Permission.find_all_by_list_id(session[:list_id]) : Permission.all

		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @permissions }
		end
	end

	# GET /permissions/1
	# GET /permissions/1.xml
	def show
		@permission = Permission.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml	{ render :xml => @permission }
		end
	end

	# GET /permissions/new
	# GET /permissions/new.xml
	def new
		@permission = Permission.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml	{ render :xml => @permission }
		end
	end

	# GET /permissions/1/edit
	def edit
		@permission = Permission.find(params[:id])
	end

	# POST /permissions
	# POST /permissions.xml
	def create
		@permission = Permission.new(params[:permission])

		respond_to do |format|
			if @permission.save
				format.html	{ redirect_to(@permission, :notice => 'Permission was successfully created.') }
				format.xml	{ render :xml => @permission, :status => :created, :location => @permission }
			else
				format.html	{ redirect_to :action => 'new', :new_permission_user_id => @permission.user_id, :not_initial_run => '1', :already_exists => false }
				format.xml	{ render :xml => @permission.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /permissions/1
	# PUT /permissions/1.xml
	def update
		@permission = Permission.find(params[:id])

		respond_to do |format|
			if @permission.update_attributes(params[:permission])
				format.html	{ redirect_to(@permission, :notice => 'Permission was successfully updated.') }
				format.xml	{ head :ok }
			else
				format.html	{ redirect_to :action => 'edit', :new_permission_user_id => @permission.user_id, :not_initial_run => '1', :already_exists => false }
				format.xml	{ render :xml => @permission.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /permissions/1
	# DELETE /permissions/1.xml
	def destroy
		@permission = Permission.find(params[:id])
		@permission.destroy

		respond_to do |format|
			format.html	{ redirect_to(permissions_url) }
			format.xml	{ head :ok }
		end
	end
end

todo/app/helpers/permissions_helper.rb
module PermissionsHelper
end

todo/app/views/permissions/_form.html.erb
<%= form_for @permission, :html => { :class => 'iform' } do |f| %>
	<% if @permission.errors.any? %>
		<div class="error_explanation">
			<h2><%= pluralize(@permission.errors.count, "error") %> encountered:</h2>

			<ul class="logo">
			<% @permission.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :add %>
		<div><%= f.check_box :add %></div>
	</div>
	<div class="field">
		<%= f.label :edit %>
		<div><%= f.check_box :edit %></div>
	</div>
	<div class="field">
		<%= f.label :del %>
		<div><%= f.check_box :del %></div>
	</div>
	<div class="field">
		<%= f.label :own %>
		<div><%= f.check_box :own %></div>
	</div>

	<%= f.text_field :user_id, :type => 'hidden', :value => (params[:new_permission_user_id] ? params[:new_permission_user_id] : @permission.user_id)  %>
	<%= f.text_field :list_id, :type => 'hidden', :value => (session[:list_id]? session[:list_id] : @permission.list_id) %>

	<%= f.submit %>
<% end %>

todo/app/views/permissions/edit.html.erb
<div class="doc">

<h1>Editing <%= User.find_by_id(@permission.user_id).username %>'s permissions</h1>

<%= render 'form' %>

<%= button_to 'Back', @permission, :method => :get %>

</div>

todo/app/views/permissions/index.html.erb
<div class="doc">

<h1>Users who can access <%= List.find_by_id(session[:list_id]).name %></h1>

<table class="control_table">
	<colgroup span="1"></colgroup>
	<colgroup span="1"></colgroup>
	<thead>
	<tr>
		<th>User</th>
		<th>Controls</th>
	</tr>
	</thead>
	<tfoot>
	<tr>
		<td>Total</td>
		<td><%= @permissions.length %></td>
	</tr>
	</tfoot>
	<tbody>
	<% @permissions.each do |permission| %>
	<tr>
		<td><%= permission.user.username %></td>
		<td><%= link_to 'See Permissions', permission %></td>
	</tr>
	<% end %>
	</tbody>
</table>

<br />

<%= link_to 'Add a new user', new_permission_path %>

</div>

todo/app/views/permissions/new.html.erb
<div class="doc">

<h1>Create a new permission</h1>

<% if (!params[:new_permission_user_id] or params[:already_exists]) and params[:not_initial_run] %>
	<div class="error_explanation">
		<h2>Error</h2>
		<p>
		<% if !params[:already_exists] %>
			Sorry! It looks like you've entered an invalid username. This user doesn't seem to exist.
		<% else %>
			Sorry! This person already has permissions to access their list. If you go back, you can go and edit their permissions.
		<% end %>
		</p>
	</div>
<% end %>

<%= form_tag("/search_for_user", :method => "get") do %>
	<%= label_tag(:username, "Search for user:", :placeholder => "Enter username here...") %>
	<%= text_field_tag('username') %>
	<%= submit_tag("Search") %>
<% end %>

<% if params[:new_permission_user_id] and !params[:already_exists] %>
<h2>Adding permissions for <%= User.find_by_id(params[:new_permission_user_id]).username %></h2>
<%= render 'form' %>
<% end %>

<%= button_to 'Back', {:controller => "permissions", :action => "index"}, :method => :get, :target => 'ui_display' %>

</div>

todo/app/views/permissions/show.html.erb
<div class="doc">

<p id="notice"><%= notice %></p>

<p>
	<b>User:</b>
	<%= @permission.user.username %>
</p>

<p>
	<b>Adding Items:</b>
	<%= @permission.add %>
</p>

<p>
	<b>Editing Existing Items:</b>
	<%= @permission.edit %>
</p>

<p>
	<b>Deleting Existing Items:</b>
	<%= @permission.del %>
</p>

<p>
	<b>Owns this list:</b>
	<%= @permission.own %>
</p>

<%= button_to 'Change ' + @permission.user.username + '\'s permissions', edit_permission_path(@permission.id), :method => :get %>
<%= button_to 'Remove ' + @permission.user.username + '\'s permissions', @permission, :method => :delete, :disabled => !(Permission.find_by_user_id_and_list_id(session[:user_id], session[:list_id]).own)%>
<%= button_to 'Back', {:controller => "permissions", :action => "index"}, :method => :get, :target => 'ui_display' %>

</div>