todo/config/routes.rb
Todo::Application.routes.draw do
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

	controller :home do
		post 'assign_list_id' => :assign_list_id
	end

	controller :application do
		get 'search_for_user' => :search_for_user
		get 'email_reminder' => :email_all_users
	end

  resources :items

  resources :lists

  resources :permissions

  resources :users

  get "home/index"

  root :to => "home#index"

end

todo/app/models/user.rb
# Code taken from Ruby-on-Rails guide
# http://guides.rubyonrails.org/active_record_validations_callbacks.html 

require 'digest/sha2'

class EmailValidator < ActiveModel::Validator
	def validate(record)
		@value = record.email
		unless @value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
			record.errors[:email] << ("is not an email")
		end
	end
end

class UsernameValidator < ActiveModel::Validator
	def validate(record)
		@value = record.username
		unless @value =~ /\A[a-z0-9_]+\Z/i
			record.errors[:username] << ("contains invalid characters")
		end
	end
end

class User < ActiveRecord::Base
	include ActiveModel::Validations
	attr_accessible :username, :email, :password, :password_confirmation, :email_confirmation
	validates :username, :presence => true, :length => {:within => 4..32}, :uniqueness => true
	validates :password, :presence => true, :length => {:within => 6..64}, :confirmation => true
	validates :password_confirmation, :presence => true, :length => {:within => 6..64}
	validates :email, :presence => true, :length => {:maximum => 64}, :uniqueness => true, :confirmation => true
	validates :email_confirmation, :presence => true, :length => {:maximum => 64}
	validates_with EmailValidator, :if => "email?"
	validates_with UsernameValidator, :if => "username?"

	#automatically generate salt and encrypts password
	before_save :encrypt_password
	before_destroy :delete_list_if_user_is_only_owner

	#Validations for referential integrity follow
	has_many :permissions, :dependent => :destroy
	has_many :lists, :through => :permissions

	def authenticate?(sub_password)
		password == encrypt(sub_password)
	end

	private 
		def encrypt_password
			self.salt = make_salt if new_record? 
			self.password = encrypt(password)
		end
		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
			#secure_hash to get a hash of current time
		end
		def encrypt(string)
			temp_string = string
			for i in 1..3 do 
				temp_string = secure_hash("#{salt}--#{temp_string}") 
			end
			temp_string
		end
		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end
		def delete_list_if_user_is_only_owner
			sql_find_lists = "SELECT l.* FROM lists l, permissions p WHERE p.own = 't' AND l.id = p.list_id AND p.user_id = " + id.to_s
			#not neat but I got incorrect behaviour when using other notation [string, args]
			puts 'entering this method!'
			del_candidates = List.find_by_sql sql_find_lists
			del_candidates.each do |l|
				perms = Permission.find_by_sql ["SELECT * FROM permissions WHERE list_id = ? AND own = 't'", l.id]
				if perms.size == 1
					puts l.id
					l.destroy
				end
			end
		end
end

todo/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

todo/app/helpers/home_helper.rb
module HomeHelper
end

todo/app/views/home/_dash.html.erb
<section id="dash">
	<%= link_to 'Edit User Profile', edit_user_path(User.find(session[:user_id])) %>
	<div class="popup" style="display: inline; padding-left: 80px;">
		<a href="#">Log Out</a>
		<div>Are you sure?<%= button_to 'Yes', logout_url, :method => :delete %></div>
	</div>
</section>

todo/app/views/home/index.html.erb
<%= render 'dash' %>
<div>
<aside id="controls">
	<section class="doc">
		<h1>Controls:</h1>
		<ul class="logo">
			<li><%= link_to 'New List', new_list_path %></li>
		</ul>
	</section>
	<section class="doc">
		<h1>Lists:</h1>
		<table class="control_table">
			<% @list_ids = User.find(session[:user_id]).lists.sort!{|l1, l2| l1.name.upcase <=> l2.name.upcase} %>
			<colgroup span="1"></colgroup>
			<colgroup span="2"></colgroup>
			<thead>
			<tr>
				<th>Name</th>
				<th colspan="2">Controls</th>
			</tr>
			</thead>
			<tfoot>
				<td>Total</td>
				<td colspan="2"><%= @list_ids.length %></td>
			</tfoot>
			<tbody>
			<% @list_ids.each do |list_id| %>
			<tr>
				<td><%= link_to List.find(list_id).name, { :controller => "items", :action => "index", :list_id => list_id, :comp => 'f' }, :target => 'ui_display' %></td>
				<td><%= button_to 'Rename', edit_list_path(List.find(list_id)), :method => :get, :disabled => !Permission.find_by_user_id_and_list_id(session[:user_id], list_id).own%></td>
				<td><%= button_to 'Delete', List.find(list_id), :confirm => 'Are you sure?', :method => :delete, :disabled => !Permission.find_by_user_id_and_list_id(session[:user_id], list_id).own%></td>
			</tr>
			<% end %>
			</tbody>
		</table>
	</section>
</aside>
<section id="views">
	<iframe name="ui_display" id="ui_display"></iframe>
</section>
</div>