todo/config/routes.rb
Todo::Application.routes.draw do
	controller :sessions do
		get 'login' => :new
		post 'login' => :create
		delete 'logout' => :destroy
	end

	controller :home do
		post 'assign_list_id' => :assign_list_id
	end

	controller :application do
		get 'search_for_user' => :search_for_user
		get 'email_reminder' => :email_all_users
	end

  resources :items

  resources :lists

  resources :permissions

  resources :users

  get "home/index"

  root :to => "home#index"

end

todo/app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, :presence => true, :length=>{:maximum => 64}
	validates :description, :length  => {:maximum => 128}
	validates :due_date, :presence => true
	validate :is_later_than_today
	#I think the date's automatically in the right format so I'm not
	#doing extra validation on it
	validates :list_id, :presence => true
#Referential integrity validation
	belongs_to :list
	validates :list, :presence => { :message => "must be a valid list" }

	def is_later_than_today
		if due_date
			unless due_date >= Date.today
				errors[:due_date] << ("must be at a future date")
			end
		end
	end
end

todo/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	layout 'embed'
	# GET /items
	# GET /items.xml
	def index
		if params[:list_id] and (is_number?(params[:list_id]))
			session[:list_id] = params[:list_id]
		end
		if !(User.find(session[:user_id]).lists.include?(List.find_by_id(session[:list_id])))
			session[:list_id] = User.find(session[:user_id]).lists[0].id
		end
		if params[:comp] and ( params[:comp] == 't' or params[:comp] == 'f' )
			@find_completed = params[:comp]
		else
			@find_completed = 'f'
		end
		@items = List.find(session[:list_id]).items.find_all_by_completed(@find_completed, :order => 'due_date, name')

		respond_to do |format|
			format.html # index.html.erb
			format.xml	{ render :xml => @items }
		end
	end

	# GET /items/1
	# GET /items/1.xml
	def show
		@item = Item.find(params[:id])

		respond_to do |format|
			format.html # show.html.erb
			format.xml	{ render :xml => @item }
		end
	end

	# GET /items/new
	# GET /items/new.xml
	def new
		@item = Item.new

		respond_to do |format|
			format.html # new.html.erb
			format.xml	{ render :xml => @item }
		end
	end

	# GET /items/1/edit
	def edit
		@item = Item.find(params[:id])
	end

	# POST /items
	# POST /items.xml
	def create
		@item = Item.new(params[:item])
		@item.list_id = session[:list_id]

		respond_to do |format|
			if @item.save
				format.html	{ redirect_to(@item, :notice => 'Item was successfully created.') }
				format.xml	{ render :xml => @item, :status => :created, :location => @item }
			else
				format.html	{ render :action => "new" }
				format.xml	{ render :xml => @item.errors, :status => :unprocessable_entity }
			end
		end
	end

	# PUT /items/1
	# PUT /items/1.xml
	def update
		@item = Item.find(params[:id])
		@item.list_id = session[:list_id]

		respond_to do |format|
			if @item.update_attributes(params[:item])
				format.html	{ redirect_to(@item, :notice => 'Item was successfully updated.') }
				format.xml	{ head :ok }
			else
				format.html	{ render :action => "edit" }
				format.xml	{ render :xml => @item.errors, :status => :unprocessable_entity }
			end
		end
	end

	# DELETE /items/1
	# DELETE /items/1.xml
	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		respond_to do |format|
			format.html	{ redirect_to :action => 'index', :comp => 'f' }
			format.xml	{ head :ok }
		end
	end
end

todo/app/helpers/items_helper.rb
module ItemsHelper
end

todo/app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'iform' } do |f| %>
	<% if @item.errors.any? %>
		<div class="error_explanation">
			<h2><%= pluralize(@item.errors.count, "error") %> encountered:</h2>

			<ul class="logo">
			<% @item.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %>
		<div><%= f.text_field :name %></div>
	</div>
	<div class="field">
		<%= f.label :description %>
		<div><%= f.text_field :description %></div>
	</div>
	<div class="field">
		<%= f.label :due_date %>
		<div><%= f.date_select :due_date %></div>
	</div>
	<div class="field">
		<%= f.label :completed %>
		<div><%= f.check_box :completed %></div>
	</div>
	<%= f.submit %>
<% end %>

todo/app/views/items/edit.html.erb
<div class="doc">

<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Back', {:controller => "items", :action => "index", :list_id => session[:list_id], :comp => 'f'}, :target => 'ui_display' %>

</div>

todo/app/views/items/index.html.erb
<div class="doc">
<h1><%= params[:comp] == 't' ? "Completed" : "Pending" %> items for <%= List.find(session[:list_id]).name %></h1>

<menu class="menu">
	<ul>
		<li><%= link_to 'New Item', new_item_path if Permission.find_by_user_id_and_list_id(session[:user_id], session[:list_id]).add %></li>
		<li><%= link_to 'See ' + (params[:comp] == 't' ? 'Pending' : 'Completed') + ' Items', {:controller => "items", :action => "index", :list_id => session[:list_id], :comp => (params[:comp] == 't' ? 'f' : 't')}, :target => 'ui_display' %></li>
		<li><%= link_to 'Share this list', {:controller => "permissions", :action => "index", :list_id => session[:list_id]}, :target => 'ui_display' if Permission.find_by_user_id_and_list_id(session[:user_id], session[:list_id]).own %></li>
	</ul>
</menu>

<table class="control_table">
	<colgroup span="2"></colgroup>
	<colgroup span="3"></colgroup>
	<thead>
	<tr>
		<th>Name</th>
		<th>Due Date</th>
		<th colspan="3">Controls</th>
	</tr>
	</thead>
	<tfoot>
	<tr>
		<td colspan="2">Total</td>
		<td colspan="3"><%= @items.length %></td>
	</tr>
	</tfoot>
	<tbody>
	<% @items.each do |item| %>
	<tr>
		<td><%= item.name %></td>
		<td><%= item.due_date %></td>
		<td><%= button_to 'Show', item, :method => :get %></td>
		<td><%= button_to 'Edit', edit_item_path(item), :method => :get, :disabled => !(Permission.find_by_user_id_and_list_id(session[:user_id], session[:list_id]).edit and params[:comp] == 'f')%></td>
		<td><%= button_to 'Delete', item, :confirm => 'Are you sure?', :method => :delete, :disabled => !(Permission.find_by_user_id_and_list_id(session[:user_id], session[:list_id]).del) %></td>
	</tr>
	<% end %>
	</tbody>
</table>
</div>

todo/app/views/items/new.html.erb
<div class="doc">

<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', {:controller => "items", :action => "index", :list_id => session[:list_id], :comp => 'f'}, :target => 'ui_display' %>

</div>

todo/app/views/items/show.html.erb
<div class="doc">

<p id="notice"><%= notice %></p>

<p>
	<b>Name:</b>
	<%= @item.name %>
</p>

<p>
	<b>Description:</b>
	<%= @item.description %>
</p>

<p>
	<b>Due Date:</b>
	<%= @item.due_date %>
</p>

<p>
	<b>Completed:</b>
	<%= @item.completed %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', {:controller => "items", :action => "index", :list_id => session[:list_id], :comp => 'f'}, :target => 'ui_display' %>

</div>